- name: Test bigip_facts
  hosts: vlab
  connection: local
 
  tasks:
      - name: Get all of the facts from my BIG-IP
        bigip_facts:
            server: "{{ inventory_hostname }}"
            user: "admin"
            password: "admin"
            include: "software,system_info"
            validate_certs: "false"
      
      - name: Mention the software
        debug:
            msg: "I have software version {{ software[0].version }}"
